#!/usr/bin/env python3
# libapplegfx-vulkan — SPIR-V → C array embedder (Phase 3.C scaffold)
# src/shaders/embed_spirv.py
#
# Copyright © 2026 Matthew Jackson
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Converts a set of .spv files into a single generated C source
# file that declares each blob as a static const uint8_t[] plus a
# paired size_t length. The output is #include'd by catalog.c.
#
# Usage:
#   embed_spirv.py <output.c> <name1>=<path1.spv> <name2>=...
#
# Each <name> becomes the base of the generated identifiers:
#   static const uint8_t lagfx_spirv_<name>[] = { ... };
#   static const size_t   lagfx_spirv_<name>_len = ...;
#
# The generated file is meant to be #include'd, not linked as a
# standalone TU — it has no header includes of its own. Consumers
# already have <stdint.h> + <stddef.h> in scope.
#
# See paravirt-re/shader-catalog-plan.md §3.2 ("bin2c / xxd -i /
# meson fs.read + embed_file()") — this script is the bin2c leg.

import os
import sys


HEADER = """/* Auto-generated by src/shaders/embed_spirv.py. Do not edit. */
/* #include'd from src/shaders/catalog.c — expects <stdint.h>/<stddef.h>
 * to already be in scope. */

"""


def emit_blob(fout, name, path):
    # Emit only the byte array; the consumer computes length via
    # sizeof(). Emitting an explicit `_len` size_t triggers the
    # unused-const warning on some toolchains when the array's
    # sizeof is taken directly in the catalog initializer.
    with open(path, 'rb') as fin:
        data = fin.read()
    fout.write(f'static const uint8_t lagfx_spirv_{name}[] = {{')
    for i, b in enumerate(data):
        if i % 12 == 0:
            fout.write('\n    ')
        fout.write(f'0x{b:02x},')
        if i % 12 != 11 and i != len(data) - 1:
            fout.write(' ')
    fout.write('\n};\n\n')


def main(argv):
    if len(argv) < 3:
        print('usage: embed_spirv.py <out.c> <name=path>...',
              file=sys.stderr)
        return 1
    out_path = argv[1]
    specs    = argv[2:]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as fout:
        fout.write(HEADER)
        for spec in specs:
            if '=' not in spec:
                print(f'bad spec: {spec!r} (expected name=path)',
                      file=sys.stderr)
                return 1
            name, path = spec.split('=', 1)
            emit_blob(fout, name, path)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
